### ISSUE TITLE
Add support for loading environment variables from a .env file

### ISSUE THREAD

**Issue by jflewis** [dotansimha/graphql-code-generator#1757]
**Is your feature request related to a problem? Please describe.**
Currently environment variables must exist on `process.env` before running the codegen cli

I'd like to be able to load and reference variables defined in a .env file in the `codegen.yml` file

**Describe the solution you'd like**

Using [dotenv](https://github.com/motdotla/dotenv) to either load a .env file if it exists or a cli flag to do so

**Describe alternatives you've considered**

* Using the programmatic approach

**Additional context**

**Comment by dotansimha** [comment]
@jflewis We support require extensions, so I think you should be able to do: `require: dotenv/config` in your `codegen.yml` and it will work.

**Comment by jflewis** [comment]
@dotansimha Sorry for the late response, haven't had an opportunity to take a look at this.

It seems that this doesn't exactly work. While the `require: dotenv/config` does load the .env file (which is great news), this action is happening _after_ the parsing of the YML. So I am unable to use .env in combination with ENV variables in the yml.

**Comment by dotansimha** [comment]
@jefflewis Ohh I see, it makes sense, because in order to get `require` values, we need to load the `yml` file. Keeping open, we'll try to find a solution for it soon.

**Comment by jefflewis** [comment]
@jflewis

**Comment by otofu-square** [comment]
It's very ugly but it'd be workaround until this issue fixed.

```
$ node --require dotenv/config ./node_modules/.bin/graphql-codegen --config codegen.yml
```

**Comment by dotansimha** [comment]
I think that allowing to specify `-r` to the codegen should do the trick (just like we can set `watch` from the cli but also from the config file).
This way, if you need something to get loaded before the codegen reads the `yml`, you can use `-r` and we'll make sure to load it before.

**Comment by dotansimha** [comment]
Implemented in: https://github.com/dotansimha/graphql-code-generator/pull/2016

**Comment by dotansimha** [comment]
Available in 1.3.0 🎉

**Comment by lednhatkhanh** [comment]
Stopped working after upgrading to 1.8.1

**Comment by dotansimha** [comment]
@lednhatkhanh I guess 1.8.0 doesn't work as well? 
@kamilkisiela can you please take a look? maybe it's related to cosmiconfig?

**Comment by dotansimha** [comment]
@lednhatkhanh it seems like loading env vars works, can you please share a reproduction in a new issue?

**Comment by cnt0705** [comment]
> Stopped working after upgrading to 1.8.1

happened to me as well.
it seems like env vars aren't loaded in the yml file even though i'm using `--require dotenv/config`

**Comment by lednhatkhanh** [comment]
@dotansimha Just checked again and it's not working, using `-r dotenv/config` and the env variables do not get loaded

**Comment by dotansimha** [comment]
Thanks, I created a new issue to track this: https://github.com/dotansimha/graphql-code-generator/issues/2722

**Comment by dotansimha** [comment]
@lednhatkhanh @cnt0705 

Fixed in: https://github.com/dotansimha/graphql-code-generator/pull/2758 
Alpha available: `1.8.2-alpha-c7249947.43`

**Comment by johnnyBira** [comment]
@dotansimha I upgraded to the latest `@graphql-codegen/cli` (`1.17.10`).
Passing this options used to work in `1.12.1` 
```sh
graphql-codegen -r dotenv/config dotenv_config_path=../../.env
```

But in `1.17.10` I'm seeing this error:

```sh
Cannot find module 'dotenv_config_path=../../.env'
```

Any input would be greatly appreciated

**Comment by dotansimha** [comment]
@johnnyBira 1.12 is pretty old. I'm not sure i'm able to compare that. 
You can use `DOTENV_CONFIG_PATH` env var for that

**Comment by johnnyBira** [comment]
Can you direct me to the docs please? @dotansimha

**Comment by dotansimha** [comment]
@johnnyBira 
`dotenv` supports setting configuration via environment variables (see https://github.com/motdotla/dotenv#preload), so instead of using a CLI flag for codegen, you can just set an environment variables that will effect `dotenv` directly.

**Comment by johnnyBira** [comment]
This makes sense. Thanks for taking the time explaining @dotansimha

**Comment by Dav3rs** [comment]
How can I use another env file like `.env.local`

**Comment by mislavlukach** [comment]
@Dav3rs 
```
DOTENV_CONFIG_PATH=.env.local graphql-codegen -r dotenv/config
```

**Comment by mecirmartin** [comment]
> nv/config

This does not work on windows though

**Comment by ardatan** [comment]
You can use cross-env to use that kind of env var definition(not related to codegen but npm scripts in general);
```
cross-env DOTENV_CONFIG_PATH=.env.local graphql-codegen -r dotenv/config
```

**Comment by mecirmartin** [comment]
@ardatan Thanks, already figured that out

**Comment by mecirmartin** [comment]
@ardatan Thanks, already figured that out

**Comment by DGVIP** [comment]
According to the example provided by [the documentation for the `--require` flag](https://www.the-guild.dev/graphql/codegen/docs/config-reference/require-field) first you have to indicate the config file location with the `--config` flag and then you can use the dotenv cli options.

Ex.
```bash
graphql-codegen --require dotenv/config --config ./codegen.yml dotenv_config_path=./.env.development.local
```

I'm currently working on Windows 11.

**Comment by LarsEjaas** [comment]
If anyone need to load `.env` variables for codegen.ts in a nextJS project I just want to place a solution here:

```typeScript
/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable no-process-env */
import { CodegenConfig } from "@graphql-codegen/cli";
import { loadEnvConfig } from "@next/env";

// @ts-ignore
loadEnvConfig(process.cwd());

const variable = process.env.VARIABLE;
```

This way you will utilize the @next/env package to load any variables from the .env file used for the NextJS project

**Comment by arcataroger** [comment]
For anyone coming across this in 2023 and getting lost in the comments, this is what I had to do make it work in the command line:

codegen.yml:
```yml
schema:
  - https://graphql.myapi.com:
      headers:
        Authorization: ${API_TOKEN} # NOT {process.env.API_TOKEN}
documents: './src/graphql/**/*.graphql'
# [...] snipped
```

.env
```
API_TOKEN=ABCDEF123467890
```

Command:
```bash
graphql-codegen --require dotenv/config
```

**Comment by nwazuo** [comment]
> If anyone need to load `.env` variables for codegen.ts in a nextJS project I just want to place a solution here:
> 
> ```ts
> /* eslint-disable @typescript-eslint/ban-ts-comment */
> /* eslint-disable no-process-env */
> import { CodegenConfig } from "@graphql-codegen/cli";
> import { loadEnvConfig } from "@next/env";
> 
> // @ts-ignore
> loadEnvConfig(process.cwd());
> 
> const variable = process.env.VARIABLE;
> ```
> 
> This way you will utilize the @next/env package to load any variables from the .env file used for the NextJS project

How to do this for a React-Vite project?

**Comment by RoblesF** [comment]
> > If anyone need to load `.env` variables for codegen.ts in a nextJS project I just want to place a solution here:
> > ```ts
> > /* eslint-disable @typescript-eslint/ban-ts-comment */
> > /* eslint-disable no-process-env */
> > import { CodegenConfig } from "@graphql-codegen/cli";
> > import { loadEnvConfig } from "@next/env";
> > 
> > // @ts-ignore
> > loadEnvConfig(process.cwd());
> > 
> > const variable = process.env.VARIABLE;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This way you will utilize the @next/env package to load any variables from the .env file used for the NextJS project
> 
> How to do this for a React-Vite project?

```ts
import { loadEnv } from 'vite';

const env = loadEnv(process.env.NODE_ENV || 'development', process.cwd(), '');

const variable = env.VARIABLE;
```
