### ISSUE TITLE
TS5083: Cannot read file '.nuxt/tsconfig.json' when pnpm run build

### ISSUE THREAD

**Issue by p3t3r67x0** [dotansimha/graphql-code-generator#8470]
Since migration from Nuxt 2.x.x to 3.0.0-rc.11 I have experienced build errors. 

Repo on GitHub
https://github.com/p3t3r67x0/nuxt-rc-netlify

Steps to reproduce

```
git clone https://github.com/p3t3r67x0/nuxt-rc-netlify.git
cd nuxt-rc-netlify
pnpm install --shamefully-hoist
pnpm run build
```

Output on `pnpm run build`

```
> @ build /home/xxxx/git/nuxt-rc-netlify
> nuxi build

Nuxi 3.0.0-rc.11                                                                                                                               12:24:50
Nuxt 3.0.0-rc.11 with Nitro 0.5.4                                                                                                              12:24:50
ℹ Using default Tailwind CSS file from runtime/tailwind.css                                                                   nuxt:tailwindcss 12:24:51

 ERROR  ⨯ Unable to compile TypeScript:                                                                                                        12:24:52
error TS5083: Cannot read file '/home/xxxx/git/nuxt-rc-netlify/.nuxt/tsconfig.json'.


  error TS5083: Cannot read file '.nuxt/tsconfig.json'.
  
  at createTSError (node_modules/.pnpm/ts-node@10.9.1_xkk4lltwku4cysulzbqoieownu/node_modules/ts-node/src/index.ts:859:12)
  at reportTSError (node_modules/.pnpm/ts-node@10.9.1_xkk4lltwku4cysulzbqoieownu/node_modules/ts-node/src/index.ts:863:19)
  at createFromPreloadedConfig (node_modules/.pnpm/ts-node@10.9.1_xkk4lltwku4cysulzbqoieownu/node_modules/ts-node/src/index.ts:874:36)
  at create (node_modules/.pnpm/ts-node@10.9.1_xkk4lltwku4cysulzbqoieownu/node_modules/ts-node/src/index.ts:624:10)
  at register (node_modules/.pnpm/ts-node@10.9.1_xkk4lltwku4cysulzbqoieownu/node_modules/ts-node/src/index.ts:591:15)
  at TypeScriptLoader (node_modules/.pnpm/cosmiconfig-typescript-loader@4.1.1_6gwvadyoit2eya4noty47wvh3e/node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js:52:54)
  at node_modules/.pnpm/@graphql-codegen+cli@2.13.6_galuui6spyi2qd2iomauvd5naq/node_modules/@graphql-codegen/cli/esm/config.js:16:18
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:533:24)

 ELIFECYCLE  Command failed with exit code 1.
```

It might be something with the file `cli/esm/config.js` on line 16 ff

```
const tsLoader = TypeScriptLoader({ transpileOnly: true });
```

It might be triggered or related to this [issue](https://github.com/Diizzayy/nuxt-graphql-client/issues/218) from the npm ackage `nuxt-graphql-client`

### Your Example Website or App

https://app.netlify.com/sites/courageous-fox-6869a5/deploys/63452ec99d718a0008201c67

### Steps to Reproduce the Bug or Issue

```
git clone https://github.com/p3t3r67x0/nuxt-rc-netlify.git
cd nuxt-rc-netlify
pnpm install --shamefully-hoist
pnpm run build
```

### Expected behavior

`pnpm run build` runs without build errors

### Platform

`pnpm dlx nuxi info`

```
.../share/pnpm/store/v3/tmp/dlx-20555    |   +1 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/xxxx/.local/share/pnpm/store/v3
  Virtual store is at:             ../../.local/share/pnpm/store/v3/tmp/dlx-20555/node_modules/.pnpm
.../share/pnpm/store/v3/tmp/dlx-20555    | Progress: resolved 2, reused 1, downloaded 0, added 1, done
Nuxi 3.0.0-rc.11
RootDir: /home/xxxx/git/nuxt-rc-netlify
Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `pnpm@7.13.4`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org
```

**Comment by eddeee888** [comment]
The upstream issue seems to be closed: https://github.com/Diizzayy/nuxt-graphql-client/issues/218
