### ISSUE TITLE
TypeError: camelCase.camelCase  is not a function

### ISSUE THREAD

**Issue by capaj** [dotansimha/graphql-code-generator#3209]
**Describe the bug**
type error

**To Reproduce**
```
gql-gen --config codegen.yml

then this:
TypeError: camelCase.camelCase 
is not a function
        at ReactApolloVisitor._buil
dHooksJSDoc (/home/capaj/work-repos
/looop/project-alpha3/node_modules/
@graphql-codegen/typescript-react-a
pollo/index.cjs.js:148:23)
        at ReactApolloVisitor._buil
dHooks (/home/capaj/work-repos/looo
p/project-alpha3/node_modules/@grap
hql-codegen/typescript-react-apollo
/index.cjs.js:176:34)
        at ReactApolloVisitor.build
Operation (/home/capaj/work-repos/l
ooop/project-alpha3/node_modules/@g
raphql-codegen/typescript-react-apo
llo/index.cjs.js:233:52)
        at ReactApolloVisitor.Opera
tionDefinition (/home/capaj/work-re
pos/looop/project-alpha3/node_modul
es/@graphql-codegen/visitor-plugin-
common/index.cjs.js:1768:33)
        at Object.visit 
(/home/capaj/work-repos/looop/proje
ct-alpha3/node_modules/graphql/lang
uage/visitor.js:242:26)
        at Object.plugin 
(/home/capaj/work-repos/looop/proje
ct-alpha3/node_modules/@graphql-cod
egen/typescript-react-apollo/index.
cjs.js:249:35)
        at executePlugin 
(/home/capaj/work-repos/looop/proje
ct-alpha3/node_modules/@graphql-cod
egen/core/index.cjs.js:60:41)
        at process._tickCallback (i
nternal/process/next_tick.js:68:7)
    TypeError: camelCase.camelCase 
is not a function
        at ReactApolloVisitor._buil
dHooksJSDoc (/home/capaj/work-repos
/looop/project-alpha3/node_modules/
@graphql-codegen/typescript-react-a
pollo/index.cjs.js:148:23)
        at ReactApolloVisitor._buil
dHooks (/home/capaj/work-repos/looo
p/project-alpha3/node_modules/@grap
hql-codegen/typescript-react-apollo
/index.cjs.js:176:34)
        at ReactApolloVisitor.build
Operation (/home/capaj/work-repos/l
ooop/project-alpha3/node_modules/@g
raphql-codegen/typescript-react-apo
llo/index.cjs.js:233:52)
        at ReactApolloVisitor.Opera
tionDefinition (/home/capaj/work-re
pos/looop/project-alpha3/node_modul
es/@graphql-codegen/visitor-plugin-
common/index.cjs.js:1768:33)
        at Object.visit 
(/home/capaj/work-repos/looop/proje
ct-alpha3/node_modules/graphql/lang
uage/visitor.js:242:26)
        at Object.plugin 
(/home/capaj/work-repos/looop/proje
ct-alpha3/node_modules/@graphql-cod
egen/typescript-react-apollo/index.
cjs.js:249:35)
        at executePlugin 
(/home/capaj/work-repos/looop/proje
ct-alpha3/node_modules/@graphql-cod
egen/core/index.cjs.js:60:41)
        at process._tickCallback (i
nternal/process/next_tick.js:68:7)
```

1. My GraphQL schema:

```graphql
I don't think it's needed, I can amend this if it is
```

2. My GraphQL operations:

```graphql
I don't think it's needed, I can amend this if it is
```

3. My `codegen.yml` config file:

```yml
overwrite: true

generates:
  front-end/src/graphql/gqlPrivateSchema.tsx:
    schema: 'gqlSchemas/private.graphql'
    documents:
      - 'front-end/**/*.gql'
      - '!front-end/src/app-admin/**'
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - add: '/* THIS IS A GENERATED FILE, DO NOT EDIT */'
  front-end/src/app-admin/graphql/gqlSuperuserSchema.tsx:
    schema: 'gqlSchemas/superuser.graphql'
    documents:
      - 'front-end/src/app-admin/**'
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - add: '/* THIS IS A GENERATED FILE, DO NOT EDIT */'
  front-end/src/graphql/gqlPrivateSchemaFragments.tsx:
    schema: 'gqlSchemas/private.graphql'
    plugins:
      - fragment-matcher
      - add: '/* THIS IS A GENERATED FILE, DO NOT EDIT */'
config:
  withHooks: true
  withHOC: false
  withComponent: false
  apolloReactHooksImportFrom: '@apollo/react-hooks'
  reactApolloVersion: 3
  scalars:
    EmailAddressWithTLD: string
    NonNegativeFloat: number
    NonNegativeInt: number
    PositiveInt: number
    DateTime: string
  namingConvention:
    enumValues: keep
hooks:
  afterOneFileWrite:
    - prettier --write

```

**Expected behavior**
no type error

**Environment:**

- OS: 
- `@graphql-codegen/...`: 1.10.1
- NodeJS: 10.17.0

**Additional context**

On 1.9.1 it compiles without any issue

**Comment by rathpc** [comment]
Also experiencing this after the latest version update

**Comment by kesne** [comment]
This was introduced in #3145

**Comment by ardatan** [comment]
Could you try with the following version? If you still have any error, please share the stack trace.

**Comment by coreylight** [comment]
Doesn't seem to fix the problem for me with version `1.10.1-alpha-c25db63c.4`

**Comment by coreylight** [comment]
I was able to get my setup working with this combination:
`@graphql-codegen/typescript-react-apollo@1.9.1`
`@graphql-codegen/cli@1.10.1-alpha-c25db63c.4`

**Comment by ardatan** [comment]
@coreylight Could you try `1.10.1-alpha-c25db63c.4` canary version for all packages (both ts-react-apollo and cli)?

**Comment by kolengri** [comment]
Same problem. `1.10.1-alpha-c25db63c.4` does not solve it for me

**Comment by kolengri** [comment]
I installed `1.8.3`. Works fine for me.

**Comment by ardatan** [comment]
https://codesandbox.io/s/friendly-glade-x1u9w
Could you help me reproduce it? You can see there is no errors in this sandbox.

**Comment by kolengri** [comment]
I've tried reproduce it here.
https://codesandbox.io/s/gifted-golick-xjg0h?fontsize=14&hidenavigation=1&theme=dark

In sandbox I have         `→ Cannot find module 'change-case' `: )
Hope it will help you

**Comment by ardatan** [comment]
@kolengri Your case is a little bit different :) `change-case` has introduced some breaking changes recently. That package is independent from codegen. But we decided to add some workaround code while loading the function by using`namingConvention`option.
`1.10.1-alpha-3fc7bb8a.6` should work for all of you :)

**Comment by PhishyFish** [comment]
Getting the camelCase error with `1.10.0` and `1.10.1-alpha-3fc7bb8a.6`. `1.9.1` works.
```yaml
overwrite: true
generates:
  src/__generated__/graphql.tsx:
    schema:
      - '../**/*.graphql'
    documents: './src/GraphQL/**/*.gql'
    plugins:
      - add: // tslint:disable
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-compatibility
  # Introspection schema for mock server
  src/__generated__/schema.json:
    schema:
      - '../**/*.graphql'
    documents: './src/GraphQL/**/*.gql'
    plugins:
      - introspection
```

**Comment by ardatan** [comment]
@PhishyFish Could you share a reproduction using codesandbox? Thanks!

**Comment by sapkra** [comment]
I installed `1.10.1-alpha-d8c376b0.18` and it fixed the problem. @ardatan Thanks.

**Comment by dotansimha** [comment]
Fixed in 1.11.0
