### ISSUE TITLE
Cannot Use WebPack Resolve Alias when Bumping from v1.9.1 to v1.10.0

### ISSUE THREAD

**Issue by ksylvest** [dotansimha/graphql-code-generator#3325]
**Describe the bug**

Attempting to generate using webpack / typescript with an `#import` statement bumping from v1.9.1 to v1.10.0 breaks when using a [resolve alias](https://webpack.js.org/configuration/resolve/). 

**To Reproduce**

1. Define a resolve alias inside a web-pack config.
    ```js
    environment.config.merge({
      resolve: {
        alias: {
          '@application': path.join(root, 'application'),
        },
      },
    });

    ```
2. Define equivalent paths in `tsconfig.json`.
    ```json
    "paths": {
      "@application/*": ["application/*"]
    }
    ```
3. Define a GQL file that imports a fragment using the alias.

    ```gql
    #import "@application/fragments/user.gql"
    query Users {
      ...user
    }
    ```

4. Run `graphql-codegen --config .codegen.yml` 

    ```
    $ graphql-codegen --config .codegen.yml
      ✔ Parse configuration
      ❯ Generate outputs
        ❯ Generate app/webpack/app_schema.tsx
          ✔ Load GraphQL schemas
          ✖ Load GraphQL documents
            → - app/webpack/application/fragments/noop.js
            Generate


     Found 1 error

      ✖ app/webpack/app_schema.tsx
        Error: Cannot find module '@application/fragments/users.gql'
        Require stack:
        - app/webpack/application/fragments/noop.js
            at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
            at resolveFileName (node_modules/@graphql-toolkit/core/node_modules/resolve-from/index.js:29:39)
            at resolveFrom (node_modules/@graphql-toolkit/core/node_modules/resolve-from/index.js:43:9)
            at module.exports (node_modules/@graphql-toolkit/core/node_modules/resolve-from/index.js:46:47)
            at resolveModuleFilePath (node_modules/@graphql-toolkit/core/index.cjs.js:358:24)
            at node_modules/@graphql-toolkit/core/index.cjs.js:391:32
            at Array.map (<anonymous>)
            at collectDefinitions (node_modules/@graphql-toolkit/core/index.cjs.js:389:34)
            at processImportSyntax (node_modules/@graphql-toolkit/core/index.cjs.js:285:11)
            at node_modules/@graphql-toolkit/core/index.cjs.js:631:27
            at Array.map (<anonymous>)
            at loadTypedefs (node_modules/@graphql-toolkit/core/index.cjs.js:605:29)
            at processTicksAndRejections (internal/process/task_queues.js:97:5)
            at async loadDocuments (node_modules/@graphql-codegen/cli/bin.js:373:31)
            at async node_modules/@graphql-codegen/cli/bin.js:732:55
            at async Task.task (node_modules/@graphql-codegen/cli/bin.js:582:17)
        Error: Cannot find module '@application/fragments/user.gql'
        Require stack:
        - app/webpack/application/fragments/noop.js
            at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
            at resolveFileName (node_modules/@graphql-toolkit/core/node_modules/resolve-from/index.js:29:39)
            at resolveFrom (node_modules/@graphql-toolkit/core/node_modules/resolve-from/index.js:43:9)
            at module.exports (node_modules/@graphql-toolkit/core/node_modules/resolve-from/index.js:46:47)
            at resolveModuleFilePath (node_modules/@graphql-toolkit/core/index.cjs.js:358:24)
            at node_modules/@graphql-toolkit/core/index.cjs.js:391:32
            at Array.map (<anonymous>)
            at collectDefinitions (node_modules/@graphql-toolkit/core/index.cjs.js:389:34)
            at processImportSyntax (node_modules/@graphql-toolkit/core/index.cjs.js:285:11)
            at node_modules/@graphql-toolkit/core/index.cjs.js:631:27
            at Array.map (<anonymous>)
            at loadTypedefs (node_modules/@graphql-toolkit/core/index.cjs.js:605:29)
            at processTicksAndRejections (internal/process/task_queues.js:97:5)
            at async loadDocuments (node_modules/@graphql-codegen/cli/bin.js:373:31)
            at async node_modules/@graphql-codegen/cli/bin.js:732:55
            at async Task.task (node_modules/@graphql-codegen/cli/bin.js:582:17)


    Something went wrong
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    ```

Using this config:

```yaml
schema: "./app/graphql/app_schema.graphql"
generates:
  "app/webpack/app_schema.tsx":
    documents: app/webpack/application/**/*.gql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      scalars:
        DateTime: string
      withComponent: false
      withHooks: true
      withHOC: false
```

**Environment:**

- OS: macOS
-
  ```
    "@graphql-codegen/cli": "^1.9.1",
    "@graphql-codegen/introspection": "^1.9.1",
    "@graphql-codegen/typescript": "^1.9.1",
    "@graphql-codegen/typescript-operations": "^1.9.1",
    "@graphql-codegen/typescript-react-apollo": "^1.9.1",
    ```
- NodeJS: v13.6.0

**Comment by lorado** [comment]
Take a look at this issue: https://github.com/dotansimha/graphql-code-generator/issues/3219

**Comment by dotansimha** [comment]
As @lorado said, using `skipGraphQLImport: true` should fix that. Also, please upgrade codegen to the latest if possible. 

Let me know if we need to reopen this.

**Comment by ksylvest** [comment]
@lorado @dotansimha thanks for the suggestion. I'm still noticing the same issue when running with `skipGraphQLImport: true` (sample PR: https://github.com/ksylvest/playground/pull/885). Do you know if anything else might be needed?

**Comment by ardatan** [comment]
Before v.1.10.0, GraphQL Toolkit was skipping `import` for documents which was a silent bug :) So actually we never supported your aliases in codegen. When we fix this `import` issue, you had problems with `import` because codegen doesn't skip `import` anymore.
https://github.com/dotansimha/graphql-code-generator/issues/3326

But we decided to disable it temporarily on purpose because of the open issues related to `import` usage in documents. So you can test it using `1.11.3-alpha-bb009c96.52` canary version and let's track this issue for the rest. 
https://github.com/dotansimha/graphql-code-generator/issues/3326

Just in case it'd better to keep `skipGraphQLImport: true` because we are planning to enable it again in next major release.
