### ISSUE TITLE
Wrong operation option types generated by typescript-react-apollo template

### ISSUE THREAD

**Issue by fohte** [dotansimha/graphql-code-generator#526]
Hi,
Thanks for this nice project and the typescript-react-apollo template :)

I found an issue in the HOC template of the typescript-react-apollo template since I upgraded it to 0.11.0.

### Versions

* `graphql-code-generator`: 0.10.7 or 0.11.0
* `graphql-codegen-typescript-react-apollo-template`: 0.11.0

### Current behavior

A gql-gen configuration:

```json
{
  "generatorConfig": {
    "noNamespaces": true,
    "resolvers": false
  }
}
```

A query:

```graphql
query getViewer {
  viewer {
    __typename
    id
    uid
  }
}
```

Run the `gql-gen` command:

```sh
yarn run gql-gen --schema ../docs/graphql/schema.json --template graphql-codegen-typescript-react-apollo-template --out ./queries/index.tsx --config ./.gqlgen.json 'queries/**/*.graphql'
```

Then, `gql-gen` generates a typescript file:

```typescript
export function GetViewerHOC<TProps = {}>(
  operationOptions: ReactApollo.OperationOption<TProps, Query, Variables>,
) {
  return ReactApollo.graphql<TProps, GetViewerQuery, GetViewerVariables>(
    gql`
      query getViewer {
        viewer {
          __typename
          id
          uid
        }
      }
    `,
    operationOptions,
  )
}
```

But, `tsc` raises an error:

```console
$ tsc -p . --noEmit
queries/index.tsx:70:64 - error TS2304: Cannot find name 'Variables'.

70   operationOptions: ReactApollo.OperationOption<TProps, Query, Variables>,
                                                                  ~~~~~~~~~
```

### Expected behavior

`operationOptions` should be the extended types `GetViewerQuery` and `GetViewerVariables`, not `Query` and `Variables`:

```typescript
export function GetViewerHOC<TProps = {}>(
  operationOptions: ReactApollo.OperationOption<TProps, GetViewerQuery, GetViewerVariables>,
) {
  return ReactApollo.graphql<TProps, GetViewerQuery, GetViewerVariables>(
    gql`
      query getViewer {
        viewer {
          __typename
          id
          uid
        }
      }
    `,
    operationOptions,
  )
}
```

**Comment by dotansimha** [comment]
For now, we released an alpha version with a fix for this:
```
Successfully published:
 - graphql-code-generator@0.12.0-alpha.821f12df
 - graphql-codegen-compiler@0.12.0-alpha.821f12df
 - graphql-codegen-core@0.12.0-alpha.821f12df
 - codegen-templates-scripts@0.12.0-alpha.821f12df
 - graphql-codegen-introspection-template@0.12.0-alpha.821f12df
 - graphql-codegen-apollo-angular-template@0.12.0-alpha.821f12df
 - graphql-codegen-typescript-mongodb-template@0.12.0-alpha.821f12df
 - graphql-codegen-typescript-react-apollo-template@0.12.0-alpha.821f12df
 - graphql-codegen-typescript-template@0.12.0-alpha.821f12df
```

**Comment by dotansimha** [comment]
Fixed in 0.12.0
