### ISSUE TITLE
Mention tsconfig-paths for codegen.ts?

### ISSUE THREAD

**Issue by neongreen** [dotansimha/graphql-code-generator#8838]
### Describe the bug

If you are using a `paths` section in your `tsconfig.json`, the `codegen.ts` config will fail to load if it exports any code from your project. This can happen, for instance, if you are using Pathos, which recommends providing the scheme as a string to the config.

```bash
❯ npm run gql-codegen

> gql-codegen
> graphql-codegen

TypeScriptLoader failed to compile TypeScript:
Cannot find module '@lib/model-settings'
Require stack:
- /Users/artyom/code/windorg/woc/lib/graphql/schema/user.ts
- /Users/artyom/code/windorg/woc/lib/graphql/schema.ts
- /Users/artyom/code/windorg/woc/codegen.ts
- /Users/artyom/code/windorg/woc/node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js
- ...
```

The solution is to add this section to your `tsconfig.json`:

```json
  "ts-node": {
    "require": [
      "tsconfig-paths/register"
    ]
  }
```

And install `npm i -D tsconfig-paths`.

I suppose this could be mentioned in the getting-started guide, but I don't know where in particular.

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Screenshots or Videos

-

### Platform

- OS: macOS
- NodeJS: 16.18.0
- `graphql` version: 16.6.0
- `@graphql-codegen/cli@2.16.2`
- `@graphql-codegen/client-preset@1.2.6`

### Codegen Config File

```ts
import type { CodegenConfig } from '@graphql-codegen/cli'
import { printSchema } from 'graphql'
import { schema } from '@lib/graphql/schema'

const config: CodegenConfig = {
  schema: printSchema(schema),
  documents: ['{components,lib,pages}/**/!(*.graphql).{ts,tsx}'],
  generates: {
    './generated/graphql/': {
      preset: 'client',
      plugins: [],
    },
  },
}

export default config
```

**Comment by saihaj** [comment]
I guess we can do some advanced sections and talk about monorepo structure? Even having this GH issue would serve the purpose.

**Comment by neongreen** [comment]
Just in case, this particular bit doesn't relate to monorepos — I just use `paths` to make import paths look nicer.

**Comment by ChristianIvicevic** [comment]
The suggestion is helpful to get started, but unfortunately I am running into issues since I include an mjs file and get further errors.
```
TypeScriptLoader failed to compile TypeScript:
require() of ES Module ./src/environment.mjs not supported.
Instead change the require of ./src/environment.mjs to a dynamic import() which is available in all CommonJS modules.
```
Regardless, the required configuration of ts-node isn't really documented and I appreciate the mention of it here in the issues.

**Comment by n1ru4l** [comment]
Related to
- https://github.com/dotansimha/graphql-code-generator/issues/8862
- https://github.com/davidtheclark/cosmiconfig/issues/224

If anyone wants to "fix" this in the upstream dependency cosmic config it would be very valuable to everyone.

**Comment by hrasoa** [comment]
Had the same issue, it is working fine with `@graphql-codegen/cli` `3.2.1` with this config:

```json
  "ts-node": {
    "require": ["tsconfig-paths/register"],
    "transpileOnly": true,
    "compilerOptions": {
      "module": "CommonJS"
    }
  }
```

It fails since `3.2.2`:

`Cannot find module '~/src/utils/error.utils'`

**Comment by will-holley** [comment]
Try `graphql-codegen --require tsconfig-paths/register --config codegen.ts`

**Comment by hrasoa** [comment]
Still not working

**Comment by hrasoa** [comment]
> Try `graphql-codegen --require tsconfig-paths/register --config codegen.ts`

I removed the `ts-node: ...` from  my`tsconfig` and added `--require tsconfig-paths/register` as you suggested, seems working.

**Comment by eddeee888** [comment]
Closing as there's universal approach here: https://github.com/dotansimha/graphql-code-generator/issues/8838#issuecomment-1560304699
