### ISSUE TITLE
typescript-operations creates typings for fragments twice since 1.15.0

### ISSUE THREAD

**Issue by darkbasic** [dotansimha/graphql-code-generator#4125]
Since I upgraded to 1.15.0 I get tons of errors like
```
src/graphql/types.tsx:3217:13 - error TS2300: Duplicate identifier 'MessageBaseFragment'.

3217 export type MessageBaseFragment = (
                 ~~~~~~~~~~~~~~~~~~~
```
For some reason the codegen creates typings for fragments twice.
I bisected it to this commit: https://github.com/dotansimha/graphql-code-generator/commit/cbd99701739d9158211b686379412e2209edd94c

So it looks like the bug is in GraphQL Tools v6: https://github.com/dotansimha/graphql-code-generator/pull/4019

**Comment by dotansimha** [comment]
@darkbasic Is it the same issue as #3990 ? it was fixed temporarily with https://github.com/dotansimha/graphql-code-generator/pull/4134  

@ardatan can you please take a look? is it related to graphql-tools?

**Comment by EirikFA** [comment]
#4134 fixed this in my project.

**Comment by darkbasic** [comment]
Fixed by https://github.com/dotansimha/graphql-code-generator/pull/4148
