### ISSUE TITLE
Cannot Use WebPack Resolve Alias when bumping @graphql-codegen/cli from v1.14.0 to v1.15.0

### ISSUE THREAD

**Issue by juliovedovatto** [dotansimha/graphql-code-generator#4113]
**Describe the bug**

After update `@graphql-codegen/cli` to `v1.15.0`, the import declarations stopped to work in `.gql` files. We use `graphql-tag` loader for importing. 

Note : kinda similar problem related on #3325

Example:

```graphql
#import '@api/fragments/media-photo.gql' // MediaPhotoFragment
#import '@api/fragments/channel.gql' // ChannelFragment

fragment CategoryFragment on Category {
 // ...
 channel {
    ...ChannelFragment
  }
  image {
    ...MediaPhotoFragment
  }
 // ...
}
```

It was working flawless using `@graphql-codegen/cli@1.14.0`, but now throws this error:

```
  Error: Cannot find module '@api/fragments/media-photo.gql'
    Require stack:
    -  [ROOT_DIR]/src/api/fragments/noop.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
        at resolveFileName ( [ROOT_DIR]/node_modules/resolve-from/index.js:29:39)
        at resolveFrom ( [ROOT_DIR]/node_modules/resolve-from/index.js:43:9)
        at module.exports ( [ROOT_DIR]/node_modules/resolve-from/index.js:46:47)
        at resolveFilePath ( [ROOT_DIR]/node_modules/@graphql-tools/import/index.cjs.js:282:20)
        at visitFile ( [ROOT_DIR]/node_modules/@graphql-tools/import/index.cjs.js:44:20)
        at visitFile ( [ROOT_DIR]/node_modules/@graphql-tools/import/index.cjs.js:169:45)
        at Object.processImport ( [ROOT_DIR]/node_modules/@graphql-tools/import/index.cjs.js:30:
17)
        at GraphQLFileLoader.load ( [ROOT_DIR]/node_modules/@graphql-tools/graphql-file-loader/i
ndex.cjs.js:44:35)
        at async loadFile ( [ROOT_DIR]/node_modules/@graphql-tools/load/index.cjs.js:48:24)
        at async  [ROOT_DIR]/node_modules/@graphql-tools/load/index.cjs.js:425:24
    Error: Cannot find module '@api/fragments/media-photo.gql'
    Require stack:
    -  [ROOT_DIR]/src/api/fragments/noop.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
        at resolveFileName ( [ROOT_DIR]/node_modules/resolve-from/index.js:29:39)
        at resolveFrom ( [ROOT_DIR]/node_modules/resolve-from/index.js:43:9)
        at module.exports ( [ROOT_DIR]/node_modules/resolve-from/index.js:46:47)
        at resolveFilePath ( [ROOT_DIR]/node_modules/@graphql-tools/import/index.cjs.js:282:20)
        at visitFile ( [ROOT_DIR]/node_modules/@graphql-tools/import/index.cjs.js:44:20)
        at visitFile ( [ROOT_DIR]/node_modules/@graphql-tools/import/index.cjs.js:169:45)
        at Object.processImport ( [ROOT_DIR]/node_modules/@graphql-tools/import/index.cjs.js:30:
17)
        at GraphQLFileLoader.load ( [ROOT_DIR]/node_modules/@graphql-tools/graphql-file-loader/i
ndex.cjs.js:44:35)
        at async loadFile ( [ROOT_DIR]/node_modules/@graphql-tools/load/index.cjs.js:48:24)
        at async  [ROOT_DIR]/node_modules/@graphql-tools/load/index.cjs.js:425:24
```

I opened a issue on `graphql-tools` repo https://github.com/ardatan/graphql-tools/issues/1544, but the author stated the problem is not with his package.

The only thing I see different is on `v1.15.0` you guys witched from `graphql-toolkit` to `graphql-tools` packages. So the path alias resolve got lost between this transition.

Codegen config

```yaml
overwrite: true
schema: "https://${API_ENDPOINT}/api"
documents: "src/**/*.gql"
generates:
  src/api/generated/schema.json:
    plugins:
      - "introspection"
  src/api/generated/fragments.ts:
    plugins:
      - add: "/* tslint:disable */\n/* eslint-disable */"
      - "typescript"
      - "typescript-graphql-files-modules"
      - "typescript-operations"
      - "fragment-matcher"

```

`tsconfig.json`
```json
{
  "paths": {
      "@/*": [
        "src/*"
      ],
      "@api/*": [
        "src/api/*"
      ]
  }
}
```

Weback config file:

```js
module.exports = {
// ...
  chainWebpack: (config) => {
   // ...
    config.resolve.alias.set('@api', path.resolve(__dirname, 'src/api'))
   // ...
  },
   // ...
}
```

Note: I tried using `skipGraphQLImport: true` option, but it didn't work.

I switched  back `@graphql-codegen/cli` to `1.14.0` in the meantime. 

**Environment**

* MacOS
* ```
  "@graphql-codegen/add": "^1.15.0",
    "@graphql-codegen/cli": "^1.15.0",
    "@graphql-codegen/fragment-matcher": "^1.15.0",
    "@graphql-codegen/introspection": "^1.15.0",
    "@graphql-codegen/typescript": "^1.15.0",
    "@graphql-codegen/typescript-graphql-files-modules": "^1.15.0",
    "@graphql-codegen/typescript-operations": "^1.15.0",
   ```
* NodeJS: v13.14.0 / v14.1.0

**Comment by dotansimha** [comment]
We are not really sure why it worked before. Let's keep tracking it under `graphql-tools`, since it's not related to codegen.
